name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js using .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc # .nvmrc 파일에서 Node.js 버전을 자동으로 읽어옵니다.

      - name: Install dependencies
        run: npm install

      - name: Run typecheck
        run: npm run typecheck

      - name: Run find-deadcode
        run: npm run find-deadcode

      - name: Run lint
        run: npm run lint
